global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost
  - job_name: 'ec2_aws_node_exporter_discovery'
    ec2_sd_configs:
      - port: 9100 # referred to nodeExporter exposed port
        #role_arn: arn:aws:iam::342241566140:role/Ec2-Instance-Role
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - ECS_ASG-2
  - job_name: ecs_CAdvisor
    ec2_sd_configs:
      - port: 9200 # referred to cAdvisor exposed port
        #role_arn: arn:aws:iam::342241566140:role/Ec2-Instance-Role
        filters:
        - name: tag:aws:autoscaling:groupName
          values:
          - ECS_ASG-2

